# Generated by Django 5.2.7 on 2025-11-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_sucursal_evento_comentario_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
    ]
